Update Backup & Restore
camunda-consulting/c8-devops-workshop pull request #30
Opened 2024-06-26 08:52 UTC by j-lindner

**Changes**
- copied starting point from https://github.com/ManuelDittmar/backup-restore-demo 
- Restructured folder structure
- `--version` on helm install
- added `helm uninstall` to cleanup
- Downloaded used files (instead of `wget`-ing them)
- Changed Validation: Cancel via Operate UI
- Added 'bash' to ```bash, so it's clickable in IntelliJ
- Correctd echo: "Restore **completed** for snapshot: $snapshot in repository: $repository" instead of "Restore **initiated** [...]"

**Please also check the updated Slides**
Slides 40 - 42: https://docs.google.com/presentation/d/1dWxsri2rKUPGqSGoXg7QQrzLSV-ZmnsodgclZEz4FZ4/edit#slide=id.g251fdc97518_0_24
--> Please add comments there and/or here. If everything looks good, please resolve the comment on the Slides directly. Thanks!

2024-06-26 09:25 UTC, j-lindner commented on 03 - Lab 3 - Backup and Restore/camunda-values.yaml
> +    host: "jensil.de"
remove own domain.

Use instead:
```
global:
  identity:
    auth:
      # Disable the Identity authentication for local development
      # it will fall back to basic-auth: demo/demo as default user
      enabled: false
```

2024-06-27 19:30 UTC, j-lindner commented on 03 - Lab 3 - Backup and Restore/camunda-values.yaml
> +    host: "jensil.de"
or maybe placeholder "YOUR_DOMAIN" would also work?

2024-06-28 10:44 UTC, jonathanlukas reviewed
I gave some hints. If they cannot be done in time, we can create issues for them.

2024-06-28 10:44 UTC, jonathanlukas commented on 03 - Lab 3 - Backup and Restore/Instructions.md
> +helm install camunda camunda/camunda-platform -f camunda-values.yaml --version 9.3.6
Shouldn't we go straight to helm chart v10?

2024-06-28 10:44 UTC, jonathanlukas commented on 03 - Lab 3 - Backup and Restore/Instructions.md
> +### Create Minio
Some instructions what each step would do is helpful, especially for folks who are not too familiar with `kubectl` or `bash` stuff.

These comments would also provide insights on the dependencies between the steps.

Here, links to docs would be nice to ensure consistency.

2024-06-28 10:44 UTC, jonathanlukas commented on 03 - Lab 3 - Backup and Restore/Instructions.md
> +kubectl delete deploy benchmark
For consistency, maybe use `kubectl delete -f`?
```suggestion
kubectl delete -f ./backup/benchmark.yaml
```

2024-06-28 10:44 UTC, jonathanlukas commented on 03 - Lab 3 - Backup and Restore/backup/zeebe-export-pause.yaml
> +          curl -X POST "http://camunda-zeebe-gateway:9600/actuator/exporting/pause" \
Use soft pause:
```suggestion
          curl -X POST "http://camunda-zeebe-gateway:9600/actuator/exporting/pause?soft=true" \
```

2024-06-28 10:44 UTC, jonathanlukas commented on 03 - Lab 3 - Backup and Restore/Instructions.md
> +kubectl delete job es-snapshot-minio-job
```suggestion
kubectl delete -f es-snapshot-minio-job.yaml
```

2024-06-30 08:00 UTC, ManuelDittmar requested changes

2024-06-30 08:00 UTC, ManuelDittmar commented on 03 - Lab 3 - Backups/Instructions.md
Also instructions for the "simple" back-up only approach should stay.

2024-09-19 14:06 UTC, j-lindner commented on 03 - Lab 3 - Backup and Restore/Instructions.md
> +helm install camunda camunda/camunda-platform -f camunda-values.yaml --version 9.3.6
( https://github.com/camunda-consulting/c8-devops-workshop/issues/31 :) )

2024-09-19 14:07 UTC, j-lindner commented on 03 - Lab 3 - Backup and Restore/Instructions.md
> +### Create Minio
created a issue for this (so I'll be able to merge this sooner, seeing this lives for 3 months by now): https://github.com/camunda-consulting/c8-devops-workshop/issues/35

2024-09-19 14:25 UTC, j-lindner commented on 03 - Lab 3 - Backups/Instructions.md
are you okay with me getting the "simple backup approach" back, but without the initContainers restore? I think the K8S Jobs approach is just so much superior, that I'd really push for that to be used (?)

2024-09-19 20:29 UTC, j-lindner commented on 03 - Lab 3 - Backups/Backup C8 SM.postman_collection.json
done

2024-09-19 20:29 UTC, j-lindner commented on 03 - Lab 3 - Backups/Instructions.md
done

2024-09-23 07:33 UTC, jonathanlukas approved these changes

2024-09-23 07:38 UTC, ManuelDittmar approved these changes

2024-09-23 07:46 UTC, merged